import { Playfair_Display, DM_Sans, Inter } from "next/font/google";
import "./globals.css";

const playfair_display = Playfair_Display({
  // variable: "--font-geist-sans",
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ["latin", 'cyrillic'],
});

const dm_sans = DM_Sans({
  // variable: "--font-geist-mono",
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ["latin"],
});

const inter = Inter({
  // variable: "--font-geist-mono",
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ["latin", 'cyrillic'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${playfair_display.className} ${dm_sans.className} ${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
